### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by woutermeuwis** [poz1/NFCForms#12]
Hi,

I am trying to build an app for scanning NFC tags, using this packet.
However when i try to build i get an error on this line of code:

`x = Xamarin.Forms.DependencyService.Get<INfcForms>() as NfcForms;`

Error:

> System.MissingMethodException
> Default constructor not found for type Poz1.NFCForms.Droid.NfcForms

Do you have an idea what might cause this?

**Comment by j-m-a-n** [comment]
I had this problem, its down to your linker options.  When set to anything but None - I got this error.  I got rid of it by creating a LinkerPleaseInclude.cs file with the following lines in it : 
    public void Include(Poz1.NFCForms.Droid.NfcForms nfc)
    {
      var poz1 = new Poz1.NFCForms.Droid.NfcForms();
    }

Although I imagine you could also reference the assemblies in the "Skip linking assemblies" area to stop the linker removing more than it should.

**Comment by fgiacomelli** [comment]
I have solved the problem using the same solution
