### ISSUE TITLE
Corrupt Package

### ISSUE THREAD

**Issue by gregduffield** [poz1/NFCForms#17]
I am trying to install the latest version (2.3.1) but I am getting the error 

> Unable to read package from path 'NFCForms.2.3.1\NFCForms.2.3.1.nupkg
File contains corrupted data.

Any ideas?

**Comment by poz1** [comment]
Hello Greg,
I’ll fix this asap ☺

Thanks for the feedback

**Comment by poz1** [comment]
Published version 2.3.2 that should fix,
please let me know if it works :)

**Comment by gregduffield** [comment]
That worked perfectly.

Thanks

Greg
