### ISSUE TITLE
Can't install package on portable project

### ISSUE THREAD

**Issue by ponsss** [poz1/NFCForms#19]
I was trying to use this library but I get this error
![cattura](https://user-images.githubusercontent.com/28305273/27070749-8d3fbfc0-501a-11e7-96e0-369b14fb093f.PNG)

Could not install package 'NFCForms 2.3.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by sorinmiroiu97** [comment]
Hi @ponsss . Please tell me, did you manage to create a xamarin.forms PCL project using the NFC library? Or did you find another library? Please tell me. Unlimited thanks in advance 👍
