### ISSUE TITLE
NfcForms OnNewIntent EmptyTag

### ISSUE THREAD

**Issue by StefanoIB** [poz1/NFCForms#25]
I try the code example in README, when i try to read an empty Tag, `x.OnNewIntent(this, intent);` throw this exception `System.Exception: Tag Error: No NDEF message found o NDEF not supported`.

My application have to react to an empty tag (to write it).

**Comment by MarcosCobena** [comment]
Hey, just a quick note: I fixed this with above PR :-)

**Comment by drajvver** [comment]
Now if only we could compile the code ourselves or get a new version on NuGet... ;)

**Comment by MarcosCobena** [comment]
(I got an e-mail from GitHub with a new comment on this thread and just answered without noticing the comment was removed. Anyway, my answer doesn't hurt.)

You actually can: simply clone the repo and apply my PR. I've already done this on my project and works fine :-)

Uploading to NuGet's another story... which fits better for @poz1 ;-)
