### ISSUE TITLE
error  when installing for windows phone

### ISSUE THREAD

**Issue by darkpowerxo** [poz1/NFCForms#4]
Could not install package 'NFCForms 2.3.0'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by poz1** [comment]
Hello, this error is due to the fact that NFCForms currently supports WP8.0 Silverlight.

I should be able to release a fix in the next few days but if you need it now you just have to download the source and change the PCL profile :)

**Comment by darkpowerxo** [comment]
thanks, you have been most helpful.
