### ISSUE TITLE
Could not install package NFCForms 2.3.0

### ISSUE THREAD

**Issue by knnethdw** [poz1/NFCForms#5]
Install-Package : Could not install package 'NFCForms 2.3.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by darkpowerxo** [comment]
go to`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\`
there are bunch of folders named Porfile + "number"
look for a number before 111 mine was 78
now open `yourproject.csproj`
then change the number for TargetFrameworkProfile
`<TargetFrameworkProfile>Profile78</TargetFrameworkProfile>`
try to install again and it will work (at least worked for me)

**Comment by poz1** [comment]
Yes, that or you can download the source and change the PCL porfile.

Sorry guys I didn't see this before. Anyway I'm working on a totally new version :)

**Comment by SudharsanKrishnamoorthy** [comment]
@soroush731, Yes I got it, thank you so much, Its working great.
